In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Array Atrributes

In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6])


In [4]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
type(a)

numpy.ndarray

In [7]:
a.shape

(6,)

In [8]:
a.ndim # Dimension Check Korer Jonnno

1

In [23]:
a.size

8

In [10]:
import numpy as np
a=np.array([[1,2,3,4],
          [5,6,7,8]])


In [11]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a.shape # it is used to know row & colum

(2, 4)

In [13]:
a.ndim

2

In [14]:
type(a)

numpy.ndarray

In [15]:
import numpy as np
c=np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])



In [16]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
c.ndim

2

In [18]:
c.shape

(3, 3)

In [19]:
type(c)

numpy.ndarray

In [20]:
c.size # determine how many elements in array

9

In [22]:
c.nbytes

36

# Array Creation

In [2]:
import numpy as np
array1=np.array([1,2,3,4,5],dtype='int')

In [4]:
array1

array([1, 2, 3, 4, 5])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.ndim

1

In [7]:
array1

array([1, 2, 3, 4, 5])

In [8]:
#To create Array
zeros=np.zeros([3,3],dtype='int')

In [9]:
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
zeros=np.zeros([3,3],dtype='float')

In [11]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
zeros=np.zeros([3,3],dtype='str')

In [13]:
zeros

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [15]:
ones=np.ones([3,3],dtype='int')

In [16]:
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
ones=np.ones([1,3],dtype='int')

In [19]:
ones

array([[1, 1, 1]])

In [20]:
ones=np.ones([5,5],dtype='int')

In [21]:
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
np.full([3,3],5,dtype='int') #To create any number array

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [23]:
num=np.full([4,4],10,dtype='float')

In [24]:
num

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [25]:
type(num)

numpy.ndarray

In [26]:
np.size

<function numpy.size(a, axis=None)>

In [27]:
num.shape

(4, 4)

In [28]:
num.ndim

2

In [30]:
#To create identity Matrix
identity=np.identity(3)

In [31]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
identity=np.identity(5,dtype='int')

In [35]:
identity

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [38]:
eye=np.eye(3,3 ,1)

In [39]:
eye

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [40]:
eye=np.eye(3,3 ,0)

In [41]:
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
eye=np.eye(3,3 ,-1)

In [43]:
eye

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [44]:
arange=np.arange(1,10,2)

In [45]:
arange

array([1, 3, 5, 7, 9])

In [46]:
arange=np.arange(1,100,10)

In [47]:
arange

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [48]:
linspace=np.linspace(1,10,10)

In [49]:
linspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [50]:
linspace=np.linspace(1,10,20)

In [51]:
linspace

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [52]:
linspace=np.linspace(1,10,100)

In [53]:
linspace

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [54]:
linspace=np.linspace(1,10,100 ,dtype='int')

In [55]:
linspace

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10])

In [56]:
linspace=np.linspace(1,10,100 ,dtype='float')

In [57]:
linspace

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [58]:
linspace=np.linspace(1,10,100 ,dtype='str')

In [59]:
linspace

array(['1.0', '1.0909090909090908', '1.1818181818181819',
       '1.2727272727272727', '1.3636363636363638', '1.4545454545454546',
       '1.5454545454545454', '1.6363636363636362', '1.7272727272727273',
       '1.8181818181818183', '1.9090909090909092', '2.0',
       '2.090909090909091', '2.1818181818181817', '2.2727272727272725',
       '2.3636363636363638', '2.4545454545454546', '2.5454545454545454',
       '2.6363636363636367', '2.7272727272727275', '2.8181818181818183',
       '2.909090909090909', '3.0', '3.090909090909091',
       '3.1818181818181817', '3.272727272727273', '3.3636363636363638',
       '3.4545454545454546', '3.5454545454545454', '3.6363636363636362',
       '3.7272727272727275', '3.8181818181818183', '3.909090909090909',
       '4.0', '4.090909090909091', '4.181818181818182',
       '4.272727272727273', '4.363636363636363', '4.454545454545455',
       '4.545454545454545', '4.636363636363637', '4.7272727272727275',
       '4.818181818181818', '4.909090909090909', '

In [60]:
linspace.size

100

In [62]:
empty=np.empty((1,5))

In [63]:
empty

array([[1., 1., 1., 1., 1.]])

#Class Four 

# Array Indexing & slicing

# Indexing

In [64]:
arr=np.array([1,2,3,4,5])

In [65]:
arr

array([1, 2, 3, 4, 5])

In [66]:
print(arr)

[1 2 3 4 5]


In [67]:
type(arr)

numpy.ndarray

In [68]:
arr.size

5

In [69]:
arr.nbytes

20

In [70]:
arr[0]

1

In [71]:
arr[3]

4

In [73]:
arr[4]

5

In [74]:
arr[-1]

5

In [75]:
arr[-4]

2

In [78]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [80]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [93]:
#To create Random array
arr2=np.random.randint(1,10,(3,3),dtype='int')

In [94]:
arr2

array([[5, 4, 4],
       [3, 6, 7],
       [8, 6, 8]])

In [83]:
arr2[0,0]

5

In [84]:
arr2[0][0]

5

In [85]:
arr2[1,1]

5

In [89]:
arr3=np.random.randint(1,10,size=(2,3,3))

In [90]:
arr3

array([[[4, 9, 1],
        [9, 2, 8],
        [2, 6, 3]],

       [[2, 2, 5],
        [2, 8, 9],
        [8, 6, 1]]])

In [104]:
arr3[0][1][1]

2

In [108]:
arr3[1,2,2]

1

In [109]:
arr3[0,1,2]

8

In [107]:
arr3[0,1,1]

2

In [100]:
arr2=np.random.randint(1,10,(2,3,3),dtype='int')

In [101]:
arr2

array([[[5, 8, 2],
        [6, 3, 9],
        [9, 5, 5]],

       [[4, 4, 9],
        [8, 3, 2],
        [2, 7, 9]]])

In [102]:
arr2=np.random.randint(1,10,size=(2,3,3),dtype='int')

In [103]:
arr2

array([[[8, 2, 3],
        [6, 8, 9],
        [5, 8, 1]],

       [[6, 6, 4],
        [3, 4, 7],
        [7, 5, 7]]])

# Slicing

In [110]:
print(arr)

[1 2 3 4 5]


In [111]:
arr[0:3] #0=index ,3=index ,upto three ,not including 3

array([1, 2, 3])

In [112]:
arr[1:3]

array([2, 3])

In [113]:
arr[2:5]

array([3, 4, 5])

In [116]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [118]:
arr1[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [119]:
arr1[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [123]:
arr1[0:2,2:4]

array([[3, 4],
       [8, 9]])

# Class Five

# Manipilating Array Shapes
1.reshape()
2.resize()
3.flatten()
4.ravel()
5.defining array shape

# reshape()

In [124]:
a=np.array([[1,2,3],[4,5,6]])

In [125]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
a.shape

(2, 3)

In [127]:
np.reshape(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [131]:
np.reshape(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
reshaped=np.reshape(a,(3,2))

In [133]:
reshaped

array([[1, 2],
       [3, 4],
       [5, 6]])

In [134]:
reshaped.shape

(3, 2)

In [135]:
a.reshape(3,2) # Alternative Process

array([[1, 2],
       [3, 4],
       [5, 6]])

# resize()

In [150]:
resized=np.resize(a,(3,3))

In [151]:
resized=np.resize(a,(3,4))

In [140]:
resized

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

# revel()

In [146]:
a=np.random.randint(1,10,(2,3)) #return a view of the array

In [147]:
a

array([[7, 4, 3],
       [2, 1, 4]])

In [148]:
a_revel=np.ravel(a) # ravel j kono array k one dimensional te convert kore

In [149]:
a_revel

array([7, 4, 3, 2, 1, 4])

# flatten()

In [152]:
a     #Return a copy of the array,allocate new memory

array([[7, 4, 3],
       [2, 1, 4]])

In [154]:
a_flattened=a.flatten()

In [155]:
a_flattened

array([7, 4, 3, 2, 1, 4])